# Generated by Django 3.2 on 2023-01-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipeingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
